CFLAGS=-Wall -g

ls:
	@echo "========输出后缀为数字的 .c 文件======="
	ls -tr *[0-9].c

all:
	@echo "=======开始编译========="
	# make ex1
	# make ex3
	ex19
	@echo "=======结束编译========="

ex19: object.o

clean:
	@echo "=======开始删除=========="
	# rm -f ex1
	# rm -f ex3
	rm -f ex19
	@echo "=======结束删除=========="
